### ISSUE TITLE
alternative login/register from another OAuth i.e.

### ISSUE THREAD

**Issue by bdart** [ikaras/yii2-app-restful#10]
Actually it is quite cool to use this as an auth service that handles different apps or resource servers. I want to use it as an central auth instance. So the only point that is missing actually for it is that I can login/register alternatively with Facebook or Google or something like this at the Auth Service.

I did this quite easy with my own rest app. But here it is more difficult because the login does not have an email or password. So providing an alternative route for the login with another Auth service seems logical and I could generate the key and death counter by my own.

But this seems messy.
**Do you have any better thought how to integrate it in your existing flow, so that this ecosystem is able to be connected by other ecosystems like FB or Twitter or what else?**

**Comment by ikaras** [comment]
My first thoughts is:
1. Create controller like `AuthController` inherit it from filsh's `DefaultController` to replace current flow to get token
2. Take a look at this [solution](https://github.com/yiisoft/yii2-authclient/blob/master/docs/guide/README.md) and try to use it: attach `auth` (or, maybe, `fbauth`) action and implement you own `onAuthSuccess` method. 
3. This method should prepare `\OAuth2\Request` object with new `grant_type` and needed data (token from FB etc.) and run `$server->handleTokenRequest($request)`. The result will be `accees_token`
4. But before it you need to create handler for your new `grant_type` (as `filsh\yii2\oauth2server\grants\UserAuthCredentials`).

I don't know if all described will be worked, I've implemented such functionality (but I plan to do it later). But you can try :)

**Comment by bdart** [comment]
Okay 1 and to 2 are clear to handle the http call correct? :)

But when I want to get in _3_ I struggle a bit. The `\OAuth2\Request` provides me what is sent with `\OAuth2\Request::createFromGlobals()`. The `handler` is clear to check if everything is fine and give a response about it.

But I don't understand how to prepare the object and how filsh attached the handler to the method.

_From the flow it would be within the method:_
get data
check if necessary data is given
validate data
run `$server->handleTokenRequest($request)` for the user

Am I right? :/

**Comment by bdart** [comment]
sorry closed it accidently

**Comment by ikaras** [comment]
Attach new grant type handler you can in configurations (look [here](https://github.com/ikaras/yii2-oauth2-rest-template/blob/master/application/api/config/common.php) lines 23-33 - attached `client_credentials`, `user_credentials`, `refresh_token`)

The main idea of "prepare request" is to set right `grant_type` (= yours grant type handler id) and token to external service. I think, you can do like this:

"""
   $request = new \OAuth2\Request([], ["grant_type" => "external_service_credentials", "token" => <token>]);
   $server->handleTokenRequest($request)
"""

About flow - yes, I think it's right!

**Comment by bdart** [comment]
My actual try was to add an extra grant_type `federation_credentials` e.g:

```
'grantTypes' => [
                'client_credentials' => [
                    'class' => 'OAuth2\GrantType\ClientCredentials',
                    'allow_public_clients' => false
                ],
                'user_credentials' => [
                    'class' => 'OAuth2\GrantType\UserCredentials'
                ],
                'refresh_token' => [
                    'class' => 'OAuth2\GrantType\RefreshToken',
                    'always_issue_new_refresh_token' => true
                ],
                'federation_credentials' => [
                    'class' => 'components\auth\ExternalCredentials'
                ]
            ],
```

`ExternalCredentials` as class should be similar to [bshaffer GrantType](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/GrantType/JwtBearer.php) ?

So this is the response from facebook e.g after the login there:

```
accessToken: "TOKENCODE"
expiresIn: 6029
signedRequest: "FANCYCODE"
userID: "123456789"
```

I post this information to a custom URL `v1/auth/token` or something like this and validate this data via my new credential in `components\auth\ExternalCredentials`.

Afterwards I can do some fancy stuff in the controller for that URL that I inherited from  filsh's one.

Actually I stuck at the new credential type for the reason that it returns an 500 error with:

```
{
  "name": "Invalid Configuration",
  "message": "Invalid grant types configuration.",
  "code": 0,
  "type": "yii\base\InvalidConfigException",
  "file": "/var/www/api/vendor/filsh/yii2-oauth2-server/Module.php",
  "line": 79,
  "stack-trace": [
    "#0 /var/www/api/vendor/filsh/yii2-oauth2-server/filters/ErrorToExceptionFilter.php(22): filsh\yii2\oauth2server\Module->getServer()",
    "#1 (): filsh\yii2\oauth2server\filters\ErrorToExceptionFilter->afterAction()",
    "#2 /var/www/api/vendor/yiisoft/yii2/base/Component.php(541): call_user_func()",
    "#3 /var/www/api/vendor/yiisoft/yii2/base/Controller.php(292): yii\base\Component->trigger()",
    "#4 /var/www/api/vendor/yiisoft/yii2/rest/Controller.php(74): yii\base\Controller->afterAction()",
    "#5 /var/www/api/vendor/yiisoft/yii2/base/Controller.php(153): yii\rest\Controller->afterAction()",
    "#6 /var/www/api/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction()",
    "#7 /var/www/api/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction()",
    "#8 /var/www/api/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest()",
    "#9 /var/www/api/application/api/www/index.php(15): yii\base\Application->run()",
    "#10 {main}"
  ]
}
```

Do I have to extend filsh's Module too? On line 134 to 143 in the `Module.php` he defines the defaults:

```
        $defaults = [
            'access_token',
            'authorization_code',
            'client_credentials',
            'client',
            'refresh_token',
            'user_credentials',
            'public_key',
            'jwt_bearer',
            'scope',
        ];
```

When adding it here I end up adding it to bshaffer's Server.php after that I end up with:

```
{
  "name": "Exception",
  "message": "storage of type \"federation_credentials\" must implement interface \"api\components\aut\ExternalCredentialsInterface\"",
  "code": 0,
  "type": "InvalidArgumentException",
  "file": "/var/www/api/vendor/bshaffer/oauth2-server-php/src/OAuth2/Server.php",
  "line": 323,
  "stack-trace": [
    "#0 /var/www/api/vendor/bshaffer/oauth2-server-php/src/OAuth2/Server.php(98): OAuth2\Server->addStorage()",
    "#1 /var/www/api/vendor/filsh/yii2-oauth2-server/Module.php(75): OAuth2\Server->__construct()",
    "#2 /var/www/api/vendor/filsh/yii2-oauth2-server/filters/ErrorToExceptionFilter.php(22): filsh\yii2\oauth2server\Module->getServer()",
    "#3 (): filsh\yii2\oauth2server\filters\ErrorToExceptionFilter->afterAction()",
    "#4 /var/www/api/vendor/yiisoft/yii2/base/Component.php(541): call_user_func()",
    "#5 /var/www/api/vendor/yiisoft/yii2/base/Controller.php(292): yii\base\Component->trigger()",
    "#6 /var/www/api/vendor/yiisoft/yii2/rest/Controller.php(74): yii\base\Controller->afterAction()",
    "#7 /var/www/api/vendor/yiisoft/yii2/base/Controller.php(153): yii\rest\Controller->afterAction()",
    "#8 /var/www/api/vendor/yiisoft/yii2/base/Module.php(455): yii\base\Controller->runAction()",
    "#9 /var/www/api/vendor/yiisoft/yii2/web/Application.php(84): yii\base\Module->runAction()",
    "#10 /var/www/api/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest()",
    "#11 /var/www/api/application/api/www/index.php(15): yii\base\Application->run()",
    "#12 {main}"
  ]
}
```

Am I on the right track or do I tweak the wrong things?

**Comment by ikaras** [comment]
Hi, @bdart 
Little code investigation gives me part of solution :)

If you define new grant type you need to create `storage` (read "model") for it to manage. So, your configs can be:

```
        'oauth2' => [
            'class' => 'filsh\yii2\oauth2server\Module',
            'options' => [
                'token_param_name' => 'access_token',
                'access_lifetime' => 3600 * 24
            ],
            'storageMap' => [
                'user_credentials' => 'api\models\User',
/* ====> */     'federation_credentials' => 'api\models\FacebookAuthModel',
            ],
            'grantTypes' => [
                                 'client_credentials' => [
                                        'class' => 'OAuth2\GrantType\ClientCredentials',
                                        'allow_public_clients' => false
                                    ],
                                    'user_credentials' => [
                                        'class' => 'OAuth2\GrantType\UserCredentials'
                                    ],
                                    'refresh_token' => [
                                        'class' => 'OAuth2\GrantType\RefreshToken',
                                        'always_issue_new_refresh_token' => true
                                    ],
                                    'federation_credentials' => [
                                        'class' => 'components\auth\ExternalCredentials'
                                ]
            ],
        ],
```

So, `FacebookAuthModel` can be ActiveRecord and your ExternalCredentials should manipulate with it. Not sure, but, maybe, you need implements from some interfaces for model, don't know, you will see errors

**Comment by bdart** [comment]
Okay finally I ended up with nearly no errors. But how do I bind the `$server` variable with the function `getServer` from filsh's module?

```
        $server = // how to access the module;
        $request = new \OAuth2\Request([], ["grant_type" => "federation_credentials", "token" => $token]);
        $response = $server->handleTokenRequest($request);
```

**Comment by ikaras** [comment]
Em, in what file do you want to get access to the server?

**Comment by bdart** [comment]
I thought in the AuthController that extends the DefaultController? Am I wrong on that?

**Comment by ikaras** [comment]
No, it's good. So, Filsh's DefaultController works with `$this->module` - to keep it, you may do this:

```
    public function init()
    {
        $this->module = \Yii::$app->getModule('oauth2');
    }

```

And than you may use `$this->module` too.

Or, in needed place use `$server = \Yii::$app->getModule('oauth2');` directly

**Comment by bdart** [comment]
I don't know why but this works:

```
    public function init()
    {
        $this->module = \Yii::$app->getModule('oauth2');
    }

```

with `$server = \Yii::$app->getModule('oauth2');` the script does not find the `handleTokenRequest` method. So with the `init()` I am fine :).

Now it is up to to the Request:

```
$request = new Request([], ["grant_type" => "federation_credentials", 'token' => \Yii::$app->getRequest()->getBodyParams()['signed_request']]);
```

It returns even it is a POST otherwise it wouldn't fire up - maybe something with the request or?:

```
{
  "name": "Method Not Allowed",
  "message": "The request method must be POST when requesting an access token",
  "code": 0,
  "status": 405,
  "type": "yii\web\HttpException"
}
```

This is actually the output of `$request` when I print it:

```
{
  "attributes": [],
  "request": {
    "grant_type": "federation_credentials",
    "token": "FANCY_CODE"
  },
  "query": [],
  "server": [],
  "files": [],
  "cookies": [],
  "headers": [],
  "content": null
}
```

When I try it with: `$request = $this->module->getRequest();`
Everything is fine instead that I get the response that `federation_credentials` are not supported

**Comment by ikaras** [comment]
Don't afraid to read source code!
Try create request object on this way:

```
$request = new \OAuth2\Request(
      [], 
     ["grant_type" => "federation_credentials", 'token' => \Yii::$app->getRequest()->getBodyParams(['signed_request']],
    [],
    [],
    [],
    ['REQUEST_METHOD' => "post"], 
)
```

**Comment by bdart** [comment]
Well it works with `$request = $this->module->getRequest();` too but my fault was that I tried to focus on the key `federation_credentials` but my object used `signed_request` :)
This was the impeding file:

```
<?php
namespace api\components\auth;

use OAuth2\GrantType\GrantTypeInterface;
use OAuth2\RequestInterface;
use OAuth2\ResponseInterface;
use OAuth2\ResponseType\AccessTokenInterface;

class ExternalCredentials implements GrantTypeInterface
{
    private $userInfo;

    protected $storage;

    public function __construct(ExternalCredentialsInterface $storage)
    {
        $this->storage = $storage;
    }

    public function getQuerystringIdentifier()
    {
        return 'signed_request';
    }

    public function validateRequest(RequestInterface $request, ResponseInterface $response)
    {
        if (!$request->request("signed_request")) {
            $response->setError(400, 'invalid_request', 'Missing parameters: "username" and "password" required');

            return null;
        }

        if (!$this->storage->checkUserCredentials($request->request("signed_request"))) {
            $response->setError(401, 'invalid_grant', 'Invalid signed request');

            return null;
        }

        $userInfo = $this->storage->getUserDetails($request->request("signed_request"));

        if (empty($userInfo)) {
            $response->setError(400, 'invalid_grant', 'Unable to retrieve user information');

            return null;
        }

        if (!isset($userInfo['user_id'])) {
            throw new \LogicException("you must set the user_id on the array returned by getUserDetails");
        }

        $this->userInfo = $userInfo;

        return true;
    }

    public function getClientId()
    {
        return null;
    }

    public function getUserId()
    {
        return $this->userInfo['user_id'];
    }

    public function getScope()
    {
        return isset($this->userInfo['scope']) ? $this->userInfo['scope'] : null;
    }

    public function createAccessToken(AccessTokenInterface $accessToken, $client_id, $user_id, $scope)
    {
        return $accessToken->createAccessToken($client_id, $user_id, $scope);
    }
}
```

UPDATE:

The to and fro took an end. Got it now too with the credentials. Thank you very much :)

**Comment by ikaras** [comment]
Great!
You're welcome!
