### ISSUE TITLE
refresh_token 400

### ISSUE THREAD

**Issue by HolmesPaul** [ikaras/yii2-app-restful#14]
Hi, What is wrong？
![qq 20150922145027](https://cloud.githubusercontent.com/assets/11832796/10012300/4c854670-6139-11e5-9d7f-21931e9bf2f6.jpg)
![qq 20150922145237](https://cloud.githubusercontent.com/assets/11832796/10012330/9ef8600e-6139-11e5-8814-c96d901390a4.jpg)

**Comment by ikaras** [comment]
Hi. Actually - I don't know. This functionality managed by Filsh's extension and I haven't tested it yet. I thing, you should:
1. Check if exists refresh token in db
2. Check if valid expiration date of it
3. If everything ok - update Filsh extension
4. If problem will be present - you can debug yourself or create/find issue in Filsh or, even, bshaffer (https://github.com/bshaffer/oauth2-server-php) extension.

Sorry, but I haven't time to check it on my local project.
