### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by mtangoo** [ikaras/yii2-app-restful#15]
Readme seem outdated and missing some thing.
If you can get time to update it it will be great

**Comment by ikaras** [comment]
Hi, @mtangoo 
Thanks. That things based on my repository or something important were released on Filsh's or bshaffer's extenstions?

Could you point out of them and I'll try to find a time to investigate them?

**Comment by mtangoo** [comment]
For example the migration part does not install the demo products until I ran
`php application/api/yiic migrate --interactive=0` Also the path should include index.php unless Mod_Rewrite .htaccess is there (which in most cases is not there)
Those are just two (as I started poking around today)

One thing that will be nice to have (see filsh/yii2-oauth2-server#43) is explaining Scopes as they play with RBAC to limit access as well as renewing expired token

**Comment by ikaras** [comment]
Makes sense! Thanks. Need to look at it
