### ISSUE TITLE
Hi, I want to expand your project.But i do not know how to do.

### ISSUE THREAD

**Issue by HolmesPaul** [ikaras/yii2-app-restful#18]
Now, My purpose is api.test.com/book/v1  &&  api.test.com/music/v1  or  api.test.com/v1/book/  &&  api.test.com//v1/music/ . But i do not know how to do , can you help me.  Thanks.

**Comment by ikaras** [comment]
Hi, am I right - you what to make several APIs on one domain? Why you don't want to use: book.api.test.com/v1 and music.api.test.com/v1? If they have one code base - use controllers for them!

**Comment by HolmesPaul** [comment]
OK, Thanks. I get it.

**Comment by ikaras** [comment]
@HolmesPaul, I can close issue? Or you will test it?
