### ISSUE TITLE
Add Explanations on how accessRules works with Scopes

### ISSUE THREAD

**Issue by mtangoo** [ikaras/yii2-app-restful#19]
It will be nice to explain this in readme as this is central to Authorization. Many of us comes thinking of RBAC which is actually not there

**Comment by ikaras** [comment]
Hi, @mtangoo.
I found a little time and described more detailed what I've done: https://github.com/ikaras/yii2-oauth2-rest-template#what-have-been-done

Hope it readable and understandable :)

**Comment by mtangoo** [comment]
Hi @ikaras for taking your time. Am going to read it and will set pr for anything I find unredable

**Comment by ikaras** [comment]
Great! I will appreciate you for your help!
 Also, if you have ideas with new features you may create PR for it and we will discuss it

Thanks

**Comment by mtangoo** [comment]
Cool
