### ISSUE TITLE
Which is the yii2-oauth2-server version used?

### ISSUE THREAD

**Issue by ghost** [ikaras/yii2-app-restful#22]
Hi, I've just installed the template, but seems the yii2-oauth2-server was updated to latest (composer is marked as *) and broke compatibility with this application. What is the original version number? Thanks!

**Comment by ikaras** [comment]
Hi, try to use version 2.0. Could you me your error?

**Comment by ghost** [comment]
Fixed, thanks... Updating filsh/yii2-oauth2-server (dev-master 0b8e535 => v2.0.0)
Do not update to 2.0.1, there are changes on Module attributes (removed $options, etc.)

Please change composer dependency, for now :)

"require": {
    "php": ">=5.4.0",
    "yiisoft/yii2": "*",
    "filsh/yii2-oauth2-server": "2.0.0"
  },

**Comment by ikaras** [comment]
Made changes: https://github.com/ikaras/yii2-oauth2-rest-template/commit/5d0888748ad60455f5f4d2789c0d19d487a2d340

Thanks
