### ISSUE TITLE
Connection refused on migrate

### ISSUE THREAD

**Issue by jlpellicer** [ikaras/yii2-app-restful#24]
Hi, I hope you can help me.
When I run the migration, the first one, I get an error **'Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [2002] Connection refused'**
This is the command: 
    /Applications/MAMP/bin/php/php5.6.10/bin/php ./yii migrate --interactive=0

and this is the db config:

``` php
    'db' => [
        'class' => 'yii\db\Connection',
        'dsn' => 'mysql:host=127.0.0.1;port:8889;dbname=asc_auth;unix_socket=/Applications/MAMP/tmp/mysql/mysql.sock',
        'username' => 'myuser',
        'password' => 'mypassword',
        'charset' => 'utf8',
    ],
```

Same error without the unix_socket part.

I checked with another Yii2 template that the db connection is working with that string.

Thank you

**Comment by ikaras** [comment]
Hi, I can't help you, I think the problem is out of my template and needs a deep investigation of your environment :(
