### ISSUE TITLE
Declaration of api\components\filters\OAuth2AccessFilter::beforeAction() should be compatible with yii\base\ActionFilter::beforeAction($action)

### ISSUE THREAD

**Issue by elim051** [ikaras/yii2-app-restful#3]
Hi, ikaras
I find a error on my server, please check, thanks. see the attachement.
![Uploading Unnamed QQ Screenshot20150608181920.png…]()

**Comment by elim051** [comment]
![unnamed qq screenshot20150608181920](https://cloud.githubusercontent.com/assets/6869709/8032822/e30053fa-0e0b-11e5-8fe5-3eab6a6f5535.png)

**Comment by ikaras** [comment]
Hi. Thanks for your issue!
Strange, I haven't this problem. Seems like you has different interfaces of methods OAuth2AccessFilter::beforeAction() and ActionFilter::beforeAction. Please, double check if you has the latest [code of OAuth2AccessFilter](https://github.com/ikaras/yii2-oauth2-rest-template/blob/master/application/api/components/filters/OAuth2AccessFilter.php) (take a look, please, on it declaration and count of parameters).

If it the same, try to remove type `Action` of `$action` parameter (in OAuth2AccessFilter) by following way:
was: `public function beforeAction(Action $action)`
should be: `public function beforeAction(Action $action)`
If the problem in it - I will make commit to fix it

**Comment by elim051** [comment]
oh, yes, I try to remove type Action in the code of [OAuth2AccessFilter](https://github.com/ikaras/yii2-oauth2-rest-template/blob/master/application/api/components/filters/OAuth2AccessFilter.php)  
public function beforeAction($action).  All is OK, Thanks for your help.
