### ISSUE TITLE
Please ,I can't requst "oauth2/token"

### ISSUE THREAD

**Issue by yedong0839** [ikaras/yii2-app-restful#5]
when request "oauth2/token" ,it responses "Client credentials were not found in the headers or body"

**Comment by ikaras** [comment]
How did you do the request? Over curl, POSTMAN or anything else? Seems like you didn't send data like:

```
{
  "grant_type":"password",
  "username":"admin@api.loc",
  "password":"123123123",
  "client_id":"testclient",
  "client_secret":"testpass"
}
```

**Comment by yedong0839** [comment]
@ikaras thank you very much

**Comment by 3880955** [comment]
谢谢，这里我起码被 卡了两天，消耗了大量时间，感谢！

**Comment by 3880955** [comment]
> How did you do the request? Over curl, POSTMAN or anything else? Seems like you didn't send data like:
> 
> ```
> {
>   "grant_type":"password",
>   "username":"admin@api.loc",
>   "password":"123123123",
>   "client_id":"testclient",
>   "client_secret":"testpass"
> }
> ```

thankyou so much!
