### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by zolek86** [ikaras/yii2-app-restful#6]
Hey, another thing I'm tackling right now is user registration, not sure how to add data OAuth2 module while registering a user, could You write something about it?

**Comment by ikaras** [comment]
Not sure whether I understood you correctly, but:
- to registrer new user you need to use `api/models/User` and just add new  recorde to users table
- to login just registered user (and waited result of registration request should be oauth2 token) - I think the best variant is to redirect user with his email/username, passwords and client info (id and key) to login api point (/oauth2/token). Else: 
  - you need prepare GET parameters with all this parameters (what sends to login api point for getting token) 
  - create `OAuth2/Request` object by `$request = \OAuth2\Request::createFromGlobals()`
  - than, for creating token,   `$response = Yii::$app->getModule('oauth2')->getServer()->handleTokenRequest($request)`
  - to get result data: `$response->getParameters()`

Not sure if this code will work (I haven't implemented this case yet) but in such way works `filsh\yii2\oauth2server\controllers\DefaultController` and it works!

**Comment by zolek86** [comment]
What I mean is that while crating a new User model (table: user) right now I don't create any data  for authorization - in table: oauth_users. So when I create a user I should also create one in oauth_users because that is the point that the authorization is made from. I'm not sure how to do that in a good way. I mean I could create new oauth_users in a crude way but that would kind kill the module encapsulation. Or is there a way to make the module authorize user data from User model?

**Comment by ikaras** [comment]
In this repository I added one user admin@api.loc:123123123 only into users table (oauth_users is empty) and authorization (getting access token) works fine, because it (authorization) makes over User::findIdentityByAccessToken().

So, you enough to add user into users table
