### ISSUE TITLE
get 400 Bad request when request to get token

### ISSUE THREAD

**Issue by mistkafka** [ikaras/yii2-app-restful#8]
After config the project. I test request public api point. It works. But when I test request to get token, it got 

```
HTTP/1.1 400 Bad Request
Host: localhost:6666
Connection: close
X-Powered-By: PHP/5.6.8
Content-Type: application/json; charset=UTF-8

{"name":"Bad Request","message":"The grant type was not specified in the request","code":0,"status":400,"type":"yii\\web\\HttpException"}~/Code/PHP/yii2-oauth2-rest
[15:21:57]--->

```

**Comment by ikaras** [comment]
Hi.
Please, give me your request (post) parameters used to get access token. Seems you forgot about `"grant_type":"password"`

**Comment by mistkafka** [comment]
ikaras.
I just change api.loc --> localhost:6666. I have add "grant_type":"password". I think the 400 Bad Request is because the follow code

```
mysql> SELECT * FROM oauth_clients;
+------------+---------------+--------------+---------------------------------------------------------+-------+---------+
| client_id  | client_secret | redirect_uri | grant_types                                             | scope | user_id |
+------------+---------------+--------------+---------------------------------------------------------+-------+---------+
| testclient | testpass      | http://fake/ | client_credentials authorization_code password implicit | NULL  |    NULL |
+------------+---------------+--------------+---------------------------------------------------------+-------+---------+
1 row in set (0.01 sec)

```

the redirect_uri is "http://fake/" which is not exist.

**Comment by ikaras** [comment]
i don't think so.
Ok, try send POST request to http://api.loc/oauth2/token with POST parameters:
`grant_type=password&username=admin@api.loc&password=123123123&client_id=testclient&client_secret=testpass`

For this purpose you can user AJAX, Postman (chrome extension) or curl.
Curl example (as described on readme):
`curl -i -H "Accept:application/json" -H "Content-Type:application/json" "http://api.loc/oauth2/token" -XPOST \
-d '{"grant_type":"password","username":"admin@api.loc","password":"123123123","client_id":"testclient","client_secret":"testpass"}'`

**Comment by alopezc** [comment]
Hi, i have the same issue, this is the content of the log

2015-08-01 00:54:23 [127.0.0.1][-][-][error][yii\web\HttpException:400] exception 'yii\web\HttpException' with message 'The grant type was not specified in the request' in E:\xampp\htdocs\yii2_rest_oath\vendor\filsh\yii2-oauth2-server\filters\ErrorToExceptionFilter.php:35
Stack trace:
#0 [internal function]: filsh\yii2\oauth2server\filters\ErrorToExceptionFilter->afterAction(Object(yii\base\ActionEvent))
#1 E:\xampp\htdocs\yii2_rest_oath\vendor\yiisoft\yii2\base\Component.php(541): call_user_func(Array, Object(yii\base\ActionEvent))
#2 E:\xampp\htdocs\yii2_rest_oath\vendor\yiisoft\yii2\base\Controller.php(292): yii\base\Component->trigger('afterAction', Object(yii\base\ActionEvent))
#3 E:\xampp\htdocs\yii2_rest_oath\vendor\yiisoft\yii2\rest\Controller.php(74): yii\base\Controller->afterAction(Object(yii\base\InlineAction), Array)
#4 E:\xampp\htdocs\yii2_rest_oath\vendor\yiisoft\yii2\base\Controller.php(153): yii\rest\Controller->afterAction(Object(yii\base\InlineAction), Array)
#5 E:\xampp\htdocs\yii2_rest_oath\vendor\yiisoft\yii2\base\Module.php(455): yii\base\Controller->runAction('token', Array)
#6 E:\xampp\htdocs\yii2_rest_oath\vendor\yiisoft\yii2\web\Application.php(83): yii\base\Module->runAction('oauth2/default/...', Array)
#7 E:\xampp\htdocs\yii2_rest_oath\vendor\yiisoft\yii2\base\Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#8 E:\xampp\htdocs\yii2_rest_oath\application\api\www\index.php(15): yii\base\Application->run()
#9 {main}
2015-08-01 00:54:23 [127.0.0.1][-][-][info][application] $_SERVER = [
    'REDIRECT_MIBDIRS' => 'E:/xampp/php/extras/mibs'
    'REDIRECT_MYSQL_HOME' => '\xampp\mysql\bin'
    'REDIRECT_OPENSSL_CONF' => 'E:/xampp/apache/bin/openssl.cnf'
    'REDIRECT_PHP_PEAR_SYSCONF_DIR' => '\xampp\php'
    'REDIRECT_PHPRC' => '\xampp\php'
    'REDIRECT_TMP' => '\xampp\tmp'
    'REDIRECT_STATUS' => '200'
    'MIBDIRS' => 'E:/xampp/php/extras/mibs'
    'MYSQL_HOME' => '\xampp\mysql\bin'
    'OPENSSL_CONF' => 'E:/xampp/apache/bin/openssl.cnf'
    'PHP_PEAR_SYSCONF_DIR' => '\xampp\php'
    'PHPRC' => '\xampp\php'
    'TMP' => '\xampp\tmp'
    'HTTP_USER_AGENT' => 'curl/7.30.0'
    'HTTP_HOST' => 'api.loc'
    'HTTP_ACCEPT' => 'application/json'
    'CONTENT_TYPE' => 'application/json'
    'CONTENT_LENGTH' => '109'
    'SystemRoot' => 'C:\WINDOWS'
    'COMSPEC' => 'C:\WINDOWS\system32\cmd.exe'
    'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.RB;.RBW'
    'WINDIR' => 'C:\WINDOWS'
    'SERVER_SIGNATURE' => '<address>Apache/2.4.10 (Win32) OpenSSL/1.0.1i Server at api.loc Port 80</address>
'
    'SERVER_SOFTWARE' => 'Apache/2.4.10 (Win32) OpenSSL/1.0.1i'
    'SERVER_NAME' => 'api.loc'
    'SERVER_ADDR' => '127.0.0.1'
    'SERVER_PORT' => '80'
    'REMOTE_ADDR' => '127.0.0.1'
    'DOCUMENT_ROOT' => 'E:/xampp/htdocs/yii2_rest_oath/application/api/www/'
    'REQUEST_SCHEME' => 'http'
    'CONTEXT_PREFIX' => ''
    'CONTEXT_DOCUMENT_ROOT' => 'E:/xampp/htdocs/yii2_rest_oath/application/api/www/'
    'SERVER_ADMIN' => 'postmaster@localhost'
    'SCRIPT_FILENAME' => 'E:/xampp/htdocs/yii2_rest_oath/application/api/www/index.php'
    'REMOTE_PORT' => '54119'
    'REDIRECT_URL' => '/oauth2/token'
    'GATEWAY_INTERFACE' => 'CGI/1.1'
    'SERVER_PROTOCOL' => 'HTTP/1.1'
    'REQUEST_METHOD' => 'POST'
    'QUERY_STRING' => ''
    'REQUEST_URI' => '/oauth2/token'
    'SCRIPT_NAME' => '/index.php'
    'PHP_SELF' => '/index.php'
    'REQUEST_TIME_FLOAT' => 1438383263.32
    'REQUEST_TIME' => 1438383263
]

**Comment by ikaras** [comment]
Hi. I need your POST params. They should be:
grant_type=password&username=admin@api.loc&password=123123123&client_id=testclient&client_secret=testpass

**Comment by alopezc** [comment]
Hi, here is my POST

![captura](https://cloud.githubusercontent.com/assets/11527552/9026919/8ba2e35e-3906-11e5-9c26-d162704e738c.PNG)

same result in postman and console

**Comment by ikaras** [comment]
Hi. Thanks. Found the problem - something wrong with yii2 json parser and transfer it to POST parameters.

So,
1. Remove header Content-Type
2. Click to your button "Form" (below the headers)
3. Full fill all parameters

Here is my screen:
![screen shot 2015-08-03 at 13 18 36](https://cloud.githubusercontent.com/assets/4718191/9035707/097e455c-39e3-11e5-9e1c-2635433c3733.png)

**Comment by anek77713** [comment]
https://github.com/bshaffer/oauth2-server-php/issues/629

this info can help
