### ISSUE TITLE
Data returned irrespective of Rules/Scope set to restrict access

### ISSUE THREAD

**Issue by hoodlumer** [ikaras/yii2-app-restful#9]
Hi there 
Could you please shed any light on where I may be going wrong? Problem is that access restrictions are not functioning for the protected and custom scopes, so any call made returns data.

User table & oauth tables set up, populated and all working.  Access Token requests for all scopes are working fine & the tables are updated too. My Controller has the same access rules as you have in ProductController.php e.g.

```
public $modelClass = '\api\common\models\Video';
    public function accessRules()
    {
        return [
            [
                'allow' => true,
                'roles' => ['?'],
            ],
            [
                'allow' => true,
                'actions' => [
                    'view',
                    'create',
                    'update',
                    'delete'
                ],
                'roles' => ['@'],
            ],
            [
                'allow' => true,
                'actions' => ['custom'],
                'roles' => ['@'],
                'scopes' => ['custom'],
            ],
            [
                'allow' => true,
                'actions' => ['protected'],
                'roles' => ['@'],
                'scopes' => ['protected'],
            ]
        ];
    }
    public function actionCustom()
    {
        return ['status' => 'ok', 'underScope' => 'custom'];
    }
    public function actionProtected()
    {
        return ['status' => 'ok', 'underScope' => 'protected'];
    }
}
```

example of a call with protected Access Token:
http://localhost:8085/v2/videos/8?access_token=e78354aae150c3a75507c86de11610badd4ab74d
![image](https://cloud.githubusercontent.com/assets/13599950/9289994/6b93266e-4379-11e5-8adf-227adefef5ad.png)

If I call http://localhost:8085/v2/videos/8/protected I get a Not Found (#404)
![image](https://cloud.githubusercontent.com/assets/13599950/9290064/3ea957b0-437c-11e5-8a0c-11d2a3ec14f4.png)

sample of the main.php

```
'controllerNamespace' => 'api\controllers',
        'defaultRoute' => 'video',
    'modules' => [
        'v1' => [
            'basePath' => '@app/modules/v1',
            'class' => 'api\modules\v1\Module'
        ],
        'v2' => [
            'basePath' => '@app/modules/v2',
            'class' => 'api\modules\v1\Module'
        ],
        'oauth2' => [
            'class' => 'filsh\yii2\oauth2server\Module',
            'tokenParamName' => 'accessToken',
            'tokenAccessLifetime' => 3600 * 24,
            'storageMap' => [
                'user_credentials' => 'api\models\User',
            ],
            'grantTypes' => [
                'user_credentials' => [
                    'class' => 'OAuth2\GrantType\UserCredentials',
                ],
                'refresh_token' => [
                    'class' => 'OAuth2\GrantType\RefreshToken',
                    'always_issue_new_refresh_token' => true
                ]
            ]
        ],
    ],
    'components' => [        
        'user' => [
            'identityClass' => 'api\models\User',
            'enableAutoLogin' => false,
            'enableSession' => false
        ],
        'authManager' => [
                    'class' => 'yii\rbac\DbManager',
        ],          
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'urlManager' => [
            'enablePrettyUrl' => true,
            'enableStrictParsing' => true,
            'showScriptName' => false,
            'rules' => [
                'POST /oauth2/<action:\w+>' => 'oauth2/default/<action>',
                [
                    'class' => 'yii\rest\UrlRule', 
                    'controller' => ['v1/video', 'v2/video'],
                    'extraPatterns' => [
                            'GET custom' => 'custom',
                            'GET protected' => 'protected',
                            ],
                    'tokens' => [
                        '{id}' => '<id:\\w+>'
                    ]

                ]
            ],        
        ],
        'request' => [
                'parsers' => [
                        'application/json' => 'yii\web\JsonParser'
                ],
                'enableCookieValidation' => true,
                'cookieValidationKey' => 'nnnnnnnnnn'
        ],          
        'response' => [
            'class' => 'yii\web\Response',
            'formatters' => [
                yii\web\Response::FORMAT_HTML => '\api\components\HtmlResponseFormatter',
            ],
            'on beforeSend' => function (\yii\base\Event $event) {
                /** @var \yii\web\Response $response */
                $response = $event->sender;
                // catch situation, when a controller hasn't been loaded
                // so no filter was loaded too. Need to understand in which format return result
                if(empty(Yii::$app->controller)) {
                    $content_neg = new \yii\filters\ContentNegotiator();
                    $content_neg->response = $response;
                    $content_neg->formats = Yii::$app->params['formats'];
                    $content_neg->negotiate();
                }
                if ($response->data !== null && Yii::$app->request->get('suppress_response_code')) {
                    $response->data = [
                        'success' => $response->isSuccessful,
                        'data' => $response->data,
                    ];
                    $response->statusCode = 200;
                }
            },
        ],
    ],
    'params' => $params,
];
```

**Comment by hoodlumer** [comment]
Hold on... typo in v2 class it was pointing at v1

```
        'v2' => [
        'basePath' => '@app/modules/v2',
        'class' => 'api\modules\v1\Module'
```

testing continues...

hmm now have 
![image](https://cloud.githubusercontent.com/assets/13599950/9293732/01dcca76-442e-11e5-8da2-6989b13280b6.png)

**Comment by hoodlumer** [comment]
adding $options back into the version of the module.php in filsh/yii2-oauth2-server extension cleared the exception but this is only a temporary solution as it looks like a complete reinstall of the stack is required to get a stable environment.

**Comment by ikaras** [comment]
Hi.
Your `actionProtected` should be available on url `http://localhost:8085/v2/videos/protected` (without id of video)

**Comment by hoodlumer** [comment]
Yes, thanks, it does now return 403 on http://localhost:8085/v2/videos/protected
My next step if to figure out why when I supply the a protected access_token i also get a 403

![image](https://cloud.githubusercontent.com/assets/13599950/9300428/bd6e8812-44bd-11e5-80ab-73be372a830e.png)

I am using filsh/yii2-oauth2-server extension 2.0. I see there is much change and debate about the use of $options and bshaffers/oauth2-server-php use of options. Should I take later releases of filsh/yii2-oauth2-server? Or do as I was thinking and do a reinstall using yii2-oauth2-server 2.0.0 and bshaffer/oauth2-server-php ~1.7.1. Any thoughts on this?

**Comment by ikaras** [comment]
I see in your configs `'tokenParamName' => 'accessToken'`, so GET parameter should have the name `accessToken` (not `access_token` or you need to change it in settings).

About new releases of dependencies - I was a little busy and missed that. I need to test my code and  make corrections in `composer.json` (set right versions of extensions) or adopt code by learning changes and release new version of template... I'll try to find time to do that. But now - I recommend to you to set previous version of filsh extension and make `composer update`, it should remove last version and install previous one.

**Comment by hoodlumer** [comment]
Hi, 
Yes good point. Too much churn on naming these params.
Thanks I will go to previous version of filsh extension.
Thanks again for assistance.

**Comment by ikaras** [comment]
And you - thanks to using!
When you get success with decreasing version you can made commit and create pull request - for faster make changes here

**Comment by hoodlumer** [comment]
@ikaras I have taken the master version of flish 608f38b which has now lead to all my original problems with the naming of token_param_name v tokenParamaName in Module.php Whatever name I use I get Setting unknown property exception

![image](https://cloud.githubusercontent.com/assets/13599950/9303748/aabf334a-44d8-11e5-9964-8be8f7c799fd.png)

I guess you may need to see how these onging changes in filsh impact your extension? I think that I will have to take the latest filsh release and see if I can figure it out? 

Maybe of interest but before I downgraded filsh to 608f38b, I did some debugging and noticed that $scope was null when passed to verifyResourceRequest leading which resulted in the a 403 result. It should have been set to 'protected'

**Comment by ikaras** [comment]
@hoodlumer , you need to back `$option` and set value as [here](https://github.com/Filsh/yii2-oauth2-server/blob/master/Module.php#L13):

```
   'options' => [
         'token_param_name' => 'accessToken',
         'access_lifetime' => 3600
     ],
```

 And double check that you transfer access token over GET parameter `accessToken`

**Comment by hoodlumer** [comment]
@ikaras  Yep I did that already. Please see my screen grab above with unknown property exception on token_param_name. I have just installed filsh 2.0.x-dev but I can go back to filsh master dist 608f38b. If you think that this is the best thing to do?

**Comment by ikaras** [comment]
@hoodlumer Your setting should be like (not sure that you've done so):

```
        'oauth2' => [
            'class' => 'filsh\yii2\oauth2server\Module',
            'options' => [
                  'token_param_name' => 'accessToken',
                  'access_lifetime' => 3600
            ],
            'storageMap' => [
                'user_credentials' => 'api\models\User',
            ],
            'grantTypes' => [
                'user_credentials' => [
                    'class' => 'OAuth2\GrantType\UserCredentials',
                ],
                'refresh_token' => [
                    'class' => 'OAuth2\GrantType\RefreshToken',
                    'always_issue_new_refresh_token' => true
                ]
            ]
        ],
```

Please double check you've removed `tokenParamName` (or token_param_name) and `tokenAccessLifetime` from the same level with `class`, `storageMap` and 'grantTypes'. They should be on `options` section

**Comment by hoodlumer** [comment]
@ikaras thanks will revert to prev filsh and double check

**Comment by hoodlumer** [comment]
@ikaras
thanks, that indeed is working on filsh master dist now that I have put options back in main.php ;-)
By working I mean that I can  create access tokens for scopes, view public, get 403 for protected and custom scope.

I am now getting a 401 on when providing the generated access token 
![image](https://cloud.githubusercontent.com/assets/13599950/9305819/318d5542-44ec-11e5-8f0f-d0bbb1bc92db.png)

so will look at debugging that.

**Comment by ikaras** [comment]
@hoodlumer 
I think the key to solution lies on you request to auth for getting access token. Could you show me POST parameter what you send for auth?!

**Comment by hoodlumer** [comment]
@ikaras 
I have it working now! it was a last token_param_name hangover
thanks again

**Comment by ikaras** [comment]
@hoodlumer 
I know :)
I'm about scopes problem and protected/custom action availability...

**Comment by hoodlumer** [comment]
@ikaras 
here are some examples 
![image](https://cloud.githubusercontent.com/assets/13599950/9306796/689cc954-44f2-11e5-8fcd-96e9e4eb5c09.png)

![image](https://cloud.githubusercontent.com/assets/13599950/9306859/e5613f24-44f2-11e5-9f92-b34119034958.png)

**Comment by ikaras** [comment]
Strange, you should have access to `protected` action with received access token... Take a look on [filter](https://github.com/ikaras/yii2-oauth2-rest-template/blob/master/application/api/components/filters/OAuth2AccessFilter.php) - here makes analyzing  availability of action as is and with scopes.

**Comment by hoodlumer** [comment]
It is working fine, sorry I mentioned that above - it was the token_param_name hangover

**Comment by ikaras** [comment]
Ah, sorry, I've understood you wrong. Great. Don't forget to close issue when you haven't new questions

**Comment by hoodlumer** [comment]
Yep np thx again
